### ISSUE TITLE
Update for Rust 2018 / recent handelbars version

### ISSUE THREAD

**Issue by Brueggus** [nickjer/handlebars_switch#1]
This is quite an useful feature! Could you possibly update this crate for recent Rust/hbs versions?

**Comment by nickjer** [comment]
Sorry, for some reason wasn't getting notifications so didn't see this until now. I am open to Pull Requests to update this.

**Comment by nickjer** [comment]
Should be updated now in [v0.4.0](https://github.com/nickjer/handlebars_switch/releases/tag/v0.4.0)
